### ISSUE TITLE
difference in preview vs Sulu data object (array vs object) - settings property

### ISSUE THREAD

**Issue by DanielRuf** [sulu/SuluHeadlessBundle#117]
It looks like there is some difference in the `settings` property.

Is this already known, a bug, feature or something else due to typecasting?

preview:

![image (4)](https://user-images.githubusercontent.com/827205/180193162-28fe5b89-07bc-43a2-9c98-b78214a4287f.png)

frontend:

![image (2)](https://user-images.githubusercontent.com/827205/180193150-c6498845-bd15-4a38-9077-2916608258ca.png)

![mage (3)](https://user-images.githubusercontent.com/827205/180193175-113b11c9-c562-4c66-8037-46f7cf05887c.png)

The logic seems to come from here:

https://github.com/sulu/SuluHeadlessBundle/blob/0.x/Content/ContentTypeResolver/BlockResolver.php#L73

`$content[$i] = ['type' => $blockPropertyType->getName(), 'settings' => $blockPropertyType->getSettings()];`

I guess in the preview it should also be an object? Not sure if it is because of the logic of `getValue()` for block properties combined with the normalization.

**Comment by alexander-schranz** [comment]
Thx for reporting. Interesting that it is even a object on the website would it expected that if empty array also there how the code is written. But good to know that it atleast is correctly normalized there. I think we need to have a deeper look at it.

If you want to have a look at it it would be interesting what `dump($blockPropertyType->getSettings());` returns you in the preview and what it returns on the website?

**Comment by DanielRuf** [comment]
> If you want to have a look at it it would be interesting what `dump($blockPropertyType->getSettings());` returns you in the preview and what it returns on the website?

In which files and locations would that be for Sulu preview and Sulu headless output?

**Comment by alexander-schranz** [comment]
The line you mention here: https://github.com/sulu/SuluHeadlessBundle/blob/0.x/Content/ContentTypeResolver/BlockResolver.php#L73

You can also use `xdebug` with a breakpoint there to debug it.

**Comment by DanielRuf** [comment]
Hm, I'm a bit confused.

> returns you in the preview **and** what it returns on the website

Is the same line called in both views?

**Comment by alexander-schranz** [comment]
> Is the same line called in both views?

Yes once you need to debug it in the preview and once when rendered on the website.

**Comment by DanielRuf** [comment]
> Yes once you need to debug it in the preview and once when rendered on the website.

Tried the given code. No change / output visible. Even no errors. Tried also `var_dump` instead of `dump`. Nothing to see.
In general I am only working with the xml / config logic here in this project and not so deep into the Sulu PHP architecture and logic.

So it seems someone else has to test this since I do not even know and am not 100% sure, if the mentioned line is the right place.

![image](https://user-images.githubusercontent.com/827205/180209798-9051f82d-dd33-4800-a0f1-348f4d1dd5fb.png)

**Comment by DanielRuf** [comment]
frontend:

![image](https://user-images.githubusercontent.com/827205/180210070-1728b0f8-2222-49ac-abcf-58e31c09dfa4.png)

preview:

![image](https://user-images.githubusercontent.com/827205/180210164-a3ae4b6d-d452-451c-9c84-3a4aec538ca3.png)

Tested with `var_dump` since `dump` did not work for both, only for preview.

**Comment by alexander-schranz** [comment]
Okay that helps a little bit. Would be itneresting where the stdClass comes from as that should also be the case then in the preview. But I think maybe its already saved that way and as the preview is not saved it is outputted this way. A workaround would be `empty($settings) ? new \stdClass() : $settings` at that line.

**Comment by DanielRuf** [comment]
> Would be itneresting where the stdClass comes from as that should also be the case then in the preview.

Definitely interesting, yes.

> But I think maybe its already saved that way and as the preview is not saved it is outputted this way.

Same happens when the page is saved + published.

![image](https://user-images.githubusercontent.com/827205/180224802-dd8569e1-e40c-4ef1-b348-58166095fead.png)

> A workaround would be `empty($settings) ? new \stdClass() : $settings` at that line.

Sounds like a feasible solution.
