### ISSUE TITLE
HTML post processing for text-editor

### ISSUE THREAD

**Issue by wachterjohannes** [sulu/SuluHeadlessBundle#16]
The text editor in sulu can contain various special HTML tags which will be resolved in the traditional system via the response listener `sulu_markup.response_listener` which calls the right parser for the current request format - but in the core there is only a HTML markup parser implemented.

We could provide an additional markup parser for JSON which crawls the JSON object and resolves all HTML fields.

See following files in sulu:

* [`Sulu\Bundle\MarkupBundle\Listener\MarkupListener`](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MarkupBundle/Listener/MarkupListener.php)
* [Service definition for `MarkupListener`](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MarkupBundle/Resources/config/services.xml#L27)
* [`Sulu\Bundle\MarkupBundle\Markup\HtmlMarkupParser`](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MarkupBundle/Markup/HtmlMarkupParser.php)
* [Service definition for `HtmlMarkupParser`](https://github.com/sulu/sulu/blob/master/src/Sulu/Bundle/MarkupBundle/Resources/config/services.xml#L20)

**Comment by alexander-schranz** [comment]
Maybe with some response header the JSON Parser could be activated or disabled, because for example in admin api's you don't want that its replaced and we should avoid context based configuration and services.

**Comment by alexander-schranz** [comment]
@wachterjohannes what if we resolve at current state in a TextEditorResolver?

**Comment by nnatter** [comment]
If these tags are used only in the `text_editor` content type, I think providing a `TextEditorResolver implements ContentTypeResolverInterface` is a good solution

**Comment by alexander-schranz** [comment]
@nnatter for headless the texteditor would be enough.
