### ISSUE TITLE
Remove compiler passes and use index_by in tags for ContentTypeResolver and DataProviderResolver

### ISSUE THREAD

**Issue by reyostallenberg** [sulu/SuluHeadlessBundle#18]
Currently tagged services `sulu_headless.content_resolver` and `sulu_headless.data_provider_resolver` for ContentTypeResolver and DataProviderResolver are 'named' by calling `getContentType` or `getDataProvider` on it and then injected in the service that needs them named.

See: https://github.com/sulu/SuluHeadlessBundle/blob/master/DependencyInjection/ContentTypeResolverCompilerPass.php#L34 and https://github.com/sulu/SuluHeadlessBundle/blob/master/DependencyInjection/DataProviderResolverCompilerPass.php#L34

This can be replaced by utilizing indexed and tagged service collections in symfony, see https://symfony.com/blog/new-in-symfony-4-3-indexed-and-tagged-service-collections

The implementation in the tagged services can be the same if we define default_index_method correctly.

I'm willing to make a PR for this the coming week(s).

**Comment by nnatter** [comment]
Using the `default_index_method` provided by symfony sound good and should not break anything 👍
