### ISSUE TITLE
Add api to get snippet areas / default snippets

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluHeadlessBundle#42]
It would be great to have a api which will return snippet areas aka. default snippets for a webspaces.

E.g.: `/_api/snippet-areas/<area_key>`

**Comment by nnatter** [comment]
I think this would be a nice addition to the bundle 👍 

Until this is implemented, it should be possible to use a `snippet_selection` with the `default` param on the page template. The selection can be hidden in the admin interface by using a `visibleCondition`.
