### ISSUE TITLE
Change View Responses for single and multi selections

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluHeadlessBundle#46]
For a single selection the `view` response currently look like this:

```php
[$data] // [1]
```

A multi selection look like this:

```php
$data // [1, 2, 3]
```

This does make the view parameter not extendable if we maybe add displayOptions or other things to our selection content types.

# Proposal

For a single selection I would like something like:

```php
[
     'id' => $data,
]
```

And for the multi selection something like:

```php
[
     'ids' => $data,
]
```

This would then also be consistent to the exist `media_selection` and `single_media_selection` which are currently using the proposed format. /cc @wachterjohannes @nnatter what do you think?

**Comment by nnatter** [comment]
Sounds good to me! 🙂
