### ISSUE TITLE
Smart content properties mapping should not fail with not exist property

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluHeadlessBundle#53]
Not all templates have the same properties but sometimes you need to load a property in smart content which could maybe not exist in all. Currently the headless bundle fail if a property is configured in pages smart content which does not exist in all templates e.g.:

```xml
<property name="pages" type="smart_content">
    <params name="properties" type="collection">
          <param name="name" value="name" />
    </params>
</property>
```

Failing line:

https://github.com/sulu/SuluHeadlessBundle/blob/1bea2a10d52a1b062311fabb067dee71a422bb91/Content/StructureResolver.php#L123

**Comment by niklasnatter** [comment]
Fixed by #95
