### ISSUE TITLE
Add api endpoint for the search

### ISSUE THREAD

**Issue by alexander-schranz** [sulu/SuluHeadlessBundle#76]
I think the headless bundle should also provide a json endpoint for the search. Maybe its just the same like the search on the default sulu skeleton which is under `/search` or `/en/search` and use instead `/search.json` and `/en/search.json`.  But it could also run like the navigation under `/_api/search`. At the end the search should return the results searched value.

**Comment by niklasnatter** [comment]
I think this is already implemented in the [`Sulu\Bundle\HeadlessBundle\Controller\SearchController`](https://github.com/sulu/SuluHeadlessBundle/blob/0.x/Controller/SearchController.php)? 🙂

**Comment by alexander-schranz** [comment]
Seems like I missed that route its really there under `/api/search` 🙈
