### ISSUE TITLE
Documentation for API endpoints

### ISSUE THREAD

**Issue by michaelzangerle** [sulu/SuluHeadlessBundle#88]
Hi guys, 

we are currently developing an app with Sulu and the HeadlessBundle in the backend and our frontend devs are a bit struggling with the APIs as those are only partially documented. So I wonder if it would make sense for you as well to have one central place to document all the available APIs and the parameters with their possible values and examples. I saw that you started documenting a bit of them here https://github.com/sulu/SuluHeadlessBundle#provide-popular-sulu-functionality-via-json-apis and somewhere in docs are also other examples but they are a bit hard to find and there are also some things missing like:

- What values do the parameters expect? e.g. `except=1` or `except=true` or just `excerpt`
- How do you retrieve snippets?

I know I can just give it a try and have a look at the code but making things obvious would make it really easy for non php devs to interact with the API. WDYT?

PS: Thanks for all the work you put in this :slightly_smiling_face:

**Comment by alexander-schranz** [comment]
> What values do the parameters expect? e.g. except=1 or except=true or just excerpt

The api is similar to the twig extension currently best is to have a look at the controller which get parameters they allow and use `bin/websiteconsole debug:router` to find the apis.

The parameter is called `excerpt` not `except`. Code is the best documentation we can currently give. 

https://github.com/sulu/SuluHeadlessBundle/blob/83562fa5e9f661642eb24007cedaa89acf05106d/Controller/NavigationController.php#L66-L68

> How do you retrieve snippets?

Only default snippets are available and the route is also available under `bin/websiteconsole debug:router` so you can get it `/../api/snippet-areas/{area}`.

Currently the bundle is still under heavy development, maybe we can in the future provide something like swagger but at current state you need to work with the symfony debug features and have a look at the code to find the correct parameters you are searching for.

**Comment by michaelzangerle** [comment]
@alexander-schranz 

> The parameter is called excerpt not except

Ah yes of course that's just a typo. 

> The api is similar to the twig extension currently best is to have a look at the controller which get parameters they allow and use bin/websiteconsole debug:router to find the apis.

I know that, but the what I was talking about are frontend developers who are not familiar with Sulu nor with Symfony nor with PHP. How should they find that out? They will always need a backend dev to look it up for them because they have no knowledge about it at all. And then we would have to create a list of the available APIs with the parameters to not do the work multiple times. But then again it's just our team that has access to this list and documentation and I imagine it would be helpful to other people as well. That's why I suggested it here.

And to be clear I am not talking about swagger docs right now (because development, a lot of work to integrate it, ...). I was thinking of one dedicated section in the docs which provides all information on all existing APIs.

**Comment by alexander-schranz** [comment]
@michaelzangerle 

I understand your point. Don't want to sound rude in my answer just wanted to give you the fastest way how you could now find out which routes are available and what parameters they accept.

I created a PR which hope make it more clear which parameters are available on the endpoints: https://github.com/sulu/SuluHeadlessBundle/pull/89. Would be nice if you could check that out and give feedback if this is something your team can work with?

**Comment by michaelzangerle** [comment]
@alexander-schranz Don't worry I understood what you meant :slightly_smiling_face: Thanks for the fast response and taking action as well. I passed the PR on to my frontend dev colleagues and will give you an update ASAP but it looks already quite nice from my point of view.

**Comment by alexander-schranz** [comment]
We merged the PR but feel still free to add there comments when we could improve there something.
