### ISSUE TITLE
Media displayOption not showing on API

### ISSUE THREAD

**Issue by lightglitch** [sulu/SuluHeadlessBundle#9]
I have a page that using blocks, each block contains a text and image. All the information is returned by the API except the displayOption selected for each image.

**Comment by alexander-schranz** [comment]
As written in the [PR](https://github.com/sulu/SuluHeadlessBundle/pull/10#issuecomment-591290668) the displayOptions is like in the normal sulu available in the [View Variable](http://docs.sulu.io/en/2.0/book/twig.html#view)
