### ISSUE TITLE
Path to vendor folder in package json example from readme

### ISSUE THREAD

**Issue by rogoit** [sulu/SuluHeadlessBundle#92]
Hi friends,

i walked my first steps here. For my project i need to fix the path here. When its a real issue I can give you a PR.

"sulu-headless-bundle": "file:../../../vendor/sulu/headless-bundle/Resources/js-website"

See you
Roland

**Comment by alexander-schranz** [comment]
Depends on where you did create the `package.json` if its in `assets/headless/` it is `../../vendor` if its in a deeper subfolder or deeper it is `../../../vendor`. So I think the example here is correct if you did store it in `assets/headless/package.json` directory.

**Comment by rogoit** [comment]
Ahh my false I stored it in public/asset ;)
