### ISSUE TITLE
External / Internal Page Types should return Target URL for smart_content (provider "pages")

### ISSUE THREAD

**Issue by thomasduenser** [sulu/SuluHeadlessBundle#97]
External / Internal Page Types should return correct Target URL when using the `smart_content` with provider `pages`. Right now the page URL is returned and the node Typ + target URL is ignored.

**Comment by niklasnatter** [comment]
Thanks for creating this issue. I think this is related to https://github.com/sulu/SuluHeadlessBundle/issues/62 and https://github.com/sulu/SuluHeadlessBundle/issues/96

**Comment by niklasnatter** [comment]
Thanks for reporting! Should be fixed by #98
